# Generated by Django 4.2.1 on 2024-05-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Vendor's Name")),
                ('contact_details', models.TextField(verbose_name='Contact Details')),
                ('address', models.TextField(verbose_name='Address')),
                ('vendor_code', models.CharField(max_length=50, unique=True, verbose_name='Vendor Code')),
                ('on_time_delivery_rate', models.FloatField(blank=True, null=True, verbose_name='On-time Delivery Rate')),
                ('quality_rating_avg', models.FloatField(blank=True, null=True, verbose_name='Quantity Rating Average')),
                ('average_response_time', models.FloatField(blank=True, null=True, verbose_name='Average Response Time')),
                ('fulfillment_rate', models.FloatField(blank=True, null=True, verbose_name='Fulfillment Rate')),
            ],
        ),
    ]
